import { defineApp } from "@takos/app-sdk";
import { HomeScreen } from "./screens/Home";
import { SettingsScreen } from "./screens/Settings";

export default defineApp({
  id: "com.example.my-app",
  name: "My takos app",
  version: "0.1.0",
  description: "Starter app generated by create-takos-app",
  screens: [HomeScreen, SettingsScreen],
  permissions: ["core:posts.read"]
});
