export const ErrorCodes = {
  // Auth / Authorization
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  OWNER_REQUIRED: "OWNER_REQUIRED",
  PLAN_REQUIRED: "PLAN_REQUIRED",
  FEATURE_UNAVAILABLE: "FEATURE_UNAVAILABLE",

  // Resources
  NOT_FOUND: "NOT_FOUND",
  OBJECT_NOT_FOUND: "OBJECT_NOT_FOUND",
  ACTOR_NOT_FOUND: "ACTOR_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  COMMUNITY_NOT_FOUND: "COMMUNITY_NOT_FOUND",
  THREAD_NOT_FOUND: "THREAD_NOT_FOUND",
  POLL_NOT_FOUND: "POLL_NOT_FOUND",
  MEDIA_NOT_FOUND: "MEDIA_NOT_FOUND",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_FORMAT: "INVALID_FORMAT",
  CONTENT_TOO_LONG: "CONTENT_TOO_LONG",
  INVALID_VISIBILITY: "INVALID_VISIBILITY",
  INVALID_OPTION: "INVALID_OPTION",

  // Duplication / Conflict
  ALREADY_EXISTS: "ALREADY_EXISTS",
  ALREADY_LIKED: "ALREADY_LIKED",
  ALREADY_VOTED: "ALREADY_VOTED",
  ALREADY_FOLLOWED: "ALREADY_FOLLOWED",
  ALREADY_MEMBER: "ALREADY_MEMBER",
  DUPLICATE_HANDLE: "DUPLICATE_HANDLE",

  // Operation restrictions
  POLL_ENDED: "POLL_ENDED",
  SINGLE_CHOICE_ONLY: "SINGLE_CHOICE_ONLY",
  RESULTS_HIDDEN: "RESULTS_HIDDEN",
  NOT_A_POLL: "NOT_A_POLL",
  SELF_ACTION_FORBIDDEN: "SELF_ACTION_FORBIDDEN",
  BLOCKED_USER: "BLOCKED_USER",
  PRIVATE_ACCOUNT: "PRIVATE_ACCOUNT",

  // Rate limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  RATE_LIMIT_MINUTE: "RATE_LIMIT_MINUTE",
  RATE_LIMIT_DAY: "RATE_LIMIT_DAY",
  AI_LIMIT_EXCEEDED: "AI_LIMIT_EXCEEDED",

  // Storage
  STORAGE_LIMIT_EXCEEDED: "STORAGE_LIMIT_EXCEEDED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  UPLOAD_FAILED: "UPLOAD_FAILED",

  // ActivityPub
  MISSING_SIGNATURE: "MISSING_SIGNATURE",
  SIGNATURE_EXPIRED: "SIGNATURE_EXPIRED",
  SIGNATURE_FUTURE: "SIGNATURE_FUTURE",
  SIGNATURE_INVALID: "SIGNATURE_INVALID",
  DIGEST_MISMATCH: "DIGEST_MISMATCH",
  KEY_MISMATCH: "KEY_MISMATCH",
  MISSING_REQUIRED_HEADER: "MISSING_REQUIRED_HEADER",
  FEDERATION_DISABLED: "FEDERATION_DISABLED",
  INSTANCE_BLOCKED: "INSTANCE_BLOCKED",

  // API access
  API_WRITE_UNAVAILABLE: "API_WRITE_UNAVAILABLE",
  API_KEY_INVALID: "API_KEY_INVALID",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",

  // AI
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  DATA_POLICY_VIOLATION: "DATA_POLICY_VIOLATION",
  ACTION_VIOLATES_NODE_POLICY: "ACTION_VIOLATES_NODE_POLICY",

  // App definition
  MANIFEST_VALIDATION_ERROR: "MANIFEST_VALIDATION_ERROR",
  HANDLER_EXECUTION_ERROR: "HANDLER_EXECUTION_ERROR",
  RESERVED_ROUTE: "RESERVED_ROUTE",
  CYCLIC_DEPENDENCY: "CYCLIC_DEPENDENCY",
  DANGEROUS_APP_PATTERN: "DANGEROUS_APP_PATTERN",
  ESBUILD_ERROR: "ESBUILD_ERROR",
  NO_COMPILER: "NO_COMPILER",

  // Audit trail
  AUDIT_INTEGRITY_VIOLATION: "AUDIT_INTEGRITY_VIOLATION",
  AUDIT_WRITE_FAILED: "AUDIT_WRITE_FAILED",

  // Sandbox
  SANDBOX_TIMEOUT: "SANDBOX_TIMEOUT",
  SANDBOX_OOM: "SANDBOX_OOM",
  SANDBOX_OUTPUT_VIOLATION: "SANDBOX_OUTPUT_VIOLATION",
  SANDBOX_SECURITY_ERROR: "SANDBOX_SECURITY_ERROR",
  TOOL_NOT_ALLOWED: "TOOL_NOT_ALLOWED",
  PERMISSION_REVOKED: "PERMISSION_REVOKED",

  // Internal
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ErrorCodeHttpStatus = {
  // Auth / Authorization
  UNAUTHORIZED: 401,
  INVALID_TOKEN: 401,
  TOKEN_EXPIRED: 401,
  FORBIDDEN: 403,
  INSUFFICIENT_PERMISSIONS: 403,
  OWNER_REQUIRED: 403,
  PLAN_REQUIRED: 402,
  FEATURE_UNAVAILABLE: 402,

  // Resources
  NOT_FOUND: 404,
  OBJECT_NOT_FOUND: 404,
  ACTOR_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  COMMUNITY_NOT_FOUND: 404,
  THREAD_NOT_FOUND: 404,
  POLL_NOT_FOUND: 404,
  MEDIA_NOT_FOUND: 404,

  // Validation
  VALIDATION_ERROR: 400,
  INVALID_INPUT: 400,
  MISSING_REQUIRED_FIELD: 400,
  INVALID_FORMAT: 400,
  CONTENT_TOO_LONG: 400,
  INVALID_VISIBILITY: 400,
  INVALID_OPTION: 400,

  // Duplication / Conflict
  ALREADY_EXISTS: 409,
  ALREADY_LIKED: 409,
  ALREADY_VOTED: 409,
  ALREADY_FOLLOWED: 409,
  ALREADY_MEMBER: 409,
  DUPLICATE_HANDLE: 409,

  // Operation restrictions
  POLL_ENDED: 400,
  SINGLE_CHOICE_ONLY: 400,
  RESULTS_HIDDEN: 403,
  NOT_A_POLL: 400,
  SELF_ACTION_FORBIDDEN: 400,
  BLOCKED_USER: 403,
  PRIVATE_ACCOUNT: 403,

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 429,
  RATE_LIMIT_MINUTE: 429,
  RATE_LIMIT_DAY: 429,
  AI_LIMIT_EXCEEDED: 429,

  // Storage
  STORAGE_LIMIT_EXCEEDED: 507,
  FILE_TOO_LARGE: 413,
  INVALID_FILE_TYPE: 400,
  UPLOAD_FAILED: 500,

  // ActivityPub
  MISSING_SIGNATURE: 401,
  SIGNATURE_EXPIRED: 401,
  SIGNATURE_FUTURE: 401,
  SIGNATURE_INVALID: 401,
  DIGEST_MISMATCH: 401,
  KEY_MISMATCH: 401,
  MISSING_REQUIRED_HEADER: 401,
  FEDERATION_DISABLED: 503,
  INSTANCE_BLOCKED: 403,

  // API access
  API_WRITE_UNAVAILABLE: 402,
  API_KEY_INVALID: 401,
  API_KEY_EXPIRED: 401,

  // AI
  AI_UNAVAILABLE: 402,
  AI_PROVIDER_ERROR: 502,
  DATA_POLICY_VIOLATION: 403,
  ACTION_VIOLATES_NODE_POLICY: 403,

  // App definition
  MANIFEST_VALIDATION_ERROR: 400,
  HANDLER_EXECUTION_ERROR: 500,
  RESERVED_ROUTE: 400,
  CYCLIC_DEPENDENCY: 400,
  DANGEROUS_APP_PATTERN: 400,
  ESBUILD_ERROR: 400,
  NO_COMPILER: 501,

  // Audit trail
  AUDIT_INTEGRITY_VIOLATION: 500,
  AUDIT_WRITE_FAILED: 500,

  // Sandbox
  SANDBOX_TIMEOUT: 408,
  SANDBOX_OOM: 500,
  SANDBOX_OUTPUT_VIOLATION: 400,
  SANDBOX_SECURITY_ERROR: 403,
  TOOL_NOT_ALLOWED: 403,
  PERMISSION_REVOKED: 403,

  // Internal
  INTERNAL_ERROR: 500,
  DATABASE_ERROR: 500,
  CONFIGURATION_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const satisfies Record<ErrorCode, number>;

export const isErrorCode = (value: unknown): value is ErrorCode =>
  typeof value === "string" && value in ErrorCodes;
