export {
  type ApiTransport,
  type AuthCheckResult,
  type AuthStrategy,
  clearYurucommuFrontendPlugin,
  type DeploymentMode,
  type FrontendPluginContextV1,
  getApiTransport,
  getAuthStrategy,
  getSlotComponents,
  type HostedInstance,
  type HostedUserInfo,
  type InstanceHealth,
  type InstanceHealthChecks,
  type LoginResult,
  registerYurucommuFrontendPlugin,
  setYurucommuFrontendPlugins,
  type SlotEntry,
  type SlotName,
  YURUCOMMU_FRONTEND_PLUGIN_API_VERSION,
  type YurucommuFrontendPluginV1,
} from "./src/lib/plugin.ts";
