export {
  YURUCOMMU_FRONTEND_PLUGIN_API_VERSION,
  type SlotName,
  type SlotEntry,
  type DeploymentMode,
  type HostedUserInfo,
  type HostedInstance,
  type InstanceHealthChecks,
  type InstanceHealth,
  type AuthCheckResult,
  type LoginResult,
  type AuthStrategy,
  type ApiTransport,
  type FrontendPluginContextV1,
  type YurucommuFrontendPluginV1,
  registerYurucommuFrontendPlugin,
  setYurucommuFrontendPlugins,
  clearYurucommuFrontendPlugin,
  getAuthStrategy,
  getApiTransport,
  getSlotComponents,
} from './src/lib/plugin.ts';
